config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  get 'reel', to: 'reel#index', as: :reel
  get 'archival', to: 'archive#index', as: :archival
  get 'video/:id', to: 'video#show', as: :video
  get 'contact', to: 'contact#index', as: :contact
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, :director, :order, :video, presence: true

  has_attached_file :image,
                    :styles => {
                      :thumb => "262X262>"
                    },
                    :default_url => "vid_missing.jpg",
                    :path => ":rails_root/public/system/images/uploads/:basename.:extension"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :video,
                    :styles => {
                      :mp4 => {
                        :geometry => "854x510", :format => 'mp4', :streaming => true,
                        :processors => [:ffmpeg, :qtfaststart]
                      },
                      :ogg => {
                        :geometry => "854x510", :format => 'ogv', :streaming => true,
                        :processors => [:ffmpeg]
                      },
                      :webm => {
                        :geometry => "854x510", :format => 'webm', :streaming => true,
                        :processors => [:ffmpeg]
                      }
                    },
                    :path => ":rails_root/public/system/media/uploads/:basename.:extension"

  validates_attachment_content_type :video,
                                    :content_type => ["video/mp4", "video/quicktime", "video/mpeg","video/mpeg4"]

  scope :reel, -> { where(archive: false) }
  scope :archive, -> { where(archive: true) }
  scope :order_asc, -> { order(:order) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @archive = Video.archive.order_asc.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
  end
end

app/controllers/reel_controller.rb
class ReelController < ApplicationController
  def index
    @videos = Video.reel.order_asc.all
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  layout 'video'

  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reel_helper.rb
module ReelHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/archive/index.html.haml
%h3.page-title archival

%section.videos
  - if @archive.count > 0
    %ul
      - @archive.each do |archive|
        %li= render 'partials/video', video: archive
  - else
    %h4.no-results No current archives

app/views/contact/index.html.haml
%table.contact
  %tbody
    %tr
      %td
        %h6.contact-header COMMERICALS
      %td
        %h6.contact-header FEATURE FILM

    %tr
      %td
        United Talent Agency
        %br
        Robert Arakelian
        %br
        +1 310 860 3741
        %br
        arakelianr@unitedtalent.com
        %br
        = link_to 'www.utaproduction.com', 'http://www.utaproduction.com', target: '_blank'
      %td
        United Talent Agency
        %br
        Pete Franciosa
        %br
        +1 310 246 6047
        %br
        franciosap@unitedtalent.com
        %br
        = link_to 'www.utaproduction.com', 'http://www.utaproduction.com', target: '_blank'

%section.divide-line
  %hr.slant.left
  %hr.slant.right

.row
  .col-md-12.contact-direct
    Brock Houghton
    %br
    Phone: 323.449.6924
    %br
    Email: brockhoughton@mac.com

app/views/home/index.html.haml
%h1 Brock Houghton
%h2 production designer

= image_tag 'home-arrows.jpg', class: 'home-arrows'

= render 'partials/navigation'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no" />
  <title>Brock Houghton | Production Designer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'mobile', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render 'partials/header' %>

  <%= yield %>

  <%= render 'partials/footer' %>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no" />
  <title>Brock Houghton | Production Designer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'mobile', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container home">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/video.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no" />
  <title>Brock Houghton | Production Designer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'videojs/video-js.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'mobile', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'videojs/videojs', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render 'partials/header' %>

  <%= yield %>

  <%= render 'partials/footer' %>
</div>

<script>
  videojs.options.flash.swf = "/assets/video-js.swf";
</script>
</body>
</html>

app/views/partials/_footer.html.haml
%footer.main
  %section{class: 'divide-line'}
    %hr{class: 'slant left'}
    %hr{class: 'slant right'}

  .copyright
    = "copyright #{Time.now.year} brock houghton - all rights reserved"

  .credit designed by: ac media designs

app/views/partials/_header.html.haml
%header.main
  %ul.social
    %li
      connect:
    %li
      = link_to 'Tumblr', 'http://brockhoughton.tumblr.com', target: '_blank', class: 'tumblr'
    %li
      = link_to 'Instagram', 'http://instagram.com/houghtonproductiondesign', target: '_blank', class: 'instagram'

  = render 'partials/navigation'

  %h1 Brock Houghton
  %h2 production designer

  .mobile-navigation
    = render 'partials/navigation'

  .clearfix

  %section{class: 'divide-line'}
    %hr{class: 'slant left'}
    %hr{class: 'slant right'}

app/views/partials/_navigation.html.haml
%nav{class: 'main'}
  %ul
    %li
      = link_to 'reel', reel_path
    %li{class: 'period'} .
    %li
      = link_to 'archival', archival_path
    %li{class: 'period'} .
    %li
      = link_to 'contact', contact_path

app/views/partials/_video.html.haml
= link_to video_path(video.id) do
  .feature-container
    .front
      %feature
        = image_tag video.image.url(:thumb), class: 'thumbnail'
        .play-button

    .back
      %feature
        = image_tag video.image.url(:thumb), class: 'thumbnail'


.title= video.title
.director= "Dir. #{video.director}"

app/views/reel/index.html.haml
%h3.page-title reel

%section.videos
  - if @videos.count > 0
    %ul
      - @videos.each do |video|
        %li= render 'partials/video', video: video
  - else
    %h4{class: 'no-results'} No Current reel

app/views/video/show.html.haml
.video-container
  %video{id: '', class: 'video-js vjs-defaukt-skin', controls: 'controls', autoplay: 'autoplay', preload: 'none', width: '854px', height: '510px', poster: @video.image.url}
    %source{src: @video.video.url(:mp4), type: 'video/mp4'}
    %source{src: @video.video.url(:webm), type: 'video/webm'}
    %source{src: @video.video.url(:ogg), type: 'video/ogg'}

.video-information
  .title= @video.title
  .director= "Dir. #{@video.director}"